//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYELER()
        {
            this.TBLCEZALAR = new HashSet<TBLCEZALAR>();
            this.TBLHAREKET = new HashSet<TBLHAREKET>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Adý boþ býrakamassýnýz")]
        [StringLength(20,ErrorMessage ="Enfazla 20 karakter girebilirsiniz")]
        public string AD { get; set; }
        [Required(ErrorMessage = "Soyadý boþ býrakamassýnýz")]
        public string SOYADI { get; set; }
        [Required(ErrorMessage = "Mail  boþ býrakamassýnýz")]
        public string MAIL { get; set; }
        [Required(ErrorMessage = "Kullanýcý Adý boþ býrakamassýnýz")]
        public string KULLANICIADI { get; set; }
        [StringLength(10, ErrorMessage = "Enfazla 10 karakter girebilirsiniz")]
        public string SIFRE { get; set; }
        public string FOTOGRAF { get; set; }
        public string TELEFON { get; set; }
        public string OKUL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCEZALAR> TBLCEZALAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHAREKET> TBLHAREKET { get; set; }
    }
}
